### PR TITLE
feat: add tvos support

### PR DESCRIPTION
**Pull request by Duell10111**
Added the TVOS dependency and made a condition for the TV lib and iOS import

### CODE REVIEW

**Comment by AlejandroAguilar99** [comment]
Hey man, after updating the package to its last version I got 'TVVLCKit/TVVLCKit.h' file not found and that makes my app crash, do you have any idea of why would that be happening?

**Comment by Duell10111** [comment]
Hey,
on which device do you have this problem.
The TVVLCKit/TVVLCKit.h should only be included on the tvOS platform. 
https://github.com/Duell10111/react-native-vlc-media-player/blob/b6e0a3629bae3e0f696e0ca6805c44c5a8c1dc50/ios/RCTVLCPlayer/RCTVLCPlayer.m#L7

**Comment by AlejandroAguilar99** [comment]
although I suppose it must be something else, since when using a previous version the app keeps crashing without errors

**Comment by Duell10111** [comment]
Here is the fix:
https://github.com/razorRun/react-native-vlc-media-player/pull/154

**Comment by Duell10111** [comment]
Otherwise you can also rollback to the previous version, as the TVOS support is the only thing that got added in the latest release. 😅

**Pull request merged**
