### PR TITLE
chore: migration to swift for ios and add new example app

### PR DESCRIPTION
**Pull request by Duell10111**
I started to migrate to swift for the ios version, added a example to be able to test it better locally and adapted some minor adaptions.

I tested it on my app reacttube and it worked well.
Unfortunally I am currently not able to invest much time into this at the moment. Therefore any contribution is welcome.

I just wanted to share what I have. 😅

### CODE REVIEW

**Comment by razorRun** [comment]
Thank you for sharing this..it might be a good idea to have this a a beta release or different version and different branch. I can add you as a contributor to the repo if you are keen on maintaining this 😊

**Comment by Duell10111** [comment]
Okay, I can keep maintaining this if you want.
I think a beta release is a good idea to verify that everything this works as expected. 😄

**Comment by razorRun** [comment]
Thanks mate, have added you as a contro

**Comment by Duell10111** [comment]
> Thank you for sharing this..it might be a good idea to have this a a beta release or different version and different branch. I can add you as a contributor to the repo if you are keen on maintaining this 😊

How would you trigger a beta release, via a github actions job or manually. 😁

**Comment by razorRun** [comment]
hey @Duell10111 
I did not released beta versions before :).
I have approved the workflow, and fee free to create manual versions

**Comment by Duell10111** [comment]
Closing this PR for the new one. 😀
https://github.com/razorRun/react-native-vlc-media-player/pull/179

**Pull request closed without merging**
